### ISSUE TITLE
"2016 Processed Information"  Tab in Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#10]
Add these fields to the Health Insurance Tab

**Comment by gocastillo** [comment]
2016 Processed Information

Note from the underground ththis part of the form is a two column of 9 items in average.

following #7

Management team and client, provides the following fields required by client.

2016 Application #
2016 Effective Date
2016 Marketplace Policy?
Total Income Used On Application
2016 Final Gross Premium
2016 Final Subsidy
2016 Heatlh Plan
2016 Final Premium After Subsidy
2016 Verification Documents Needed

Development team translates to both camel case and underscore variables.

applicationNumber2016 application_#_2016
effectiveDate2016 effective_date_2016
marketplacePolicy2016 marketplace_policy_2016
totalIncomeUsedOnApplication total_income_used_on_application
finalGrossPremium2016 final_gross_premium_2016
finalSubsidy2016 final_subsidy_2016
heatlhPlan2016 heatlh_plan_2016
finalPremiumAfterSubsidy2016 final_premium_after_subsidy_2016
verificationDocumentsNeeded2016 verification_documents_needed_2016

For HTML ids we use the follow format:

application-#-2016
effective-date-2016
marketplace-policy-2016-?
total-income-used-on-application
final-gross-premium-2016
final-subsidy-2016
heatlh-plan-2016
final-premium-after-subsidy-2016
verification-documents-needed-2016

HTML Translate strings:

applicationNumber2016: "2016 Application #",
effectiveDate2016: "2016 Effective Date",
marketplacePolicy2016: "2016 Marketplace Policy?",
totalIncomeUsedOnApplication: "Total Income Used On Application",
finalGrossPremium2016: "2016 Final Gross Premium",
finalSubsidy2016: "2016 Final Subsidy",
healthPLan2016: "2016 Heatlh Plan",
finalPremiumAfterSubsidy2016: "2016 Final Premium After Subsidy",
verificationDocumentsNeeded2016: "2016 Verification Documents Needed",

**Comment by gocastillo** [comment]
Add these to the form in the Health Insurance Tab, at the bottom

**Comment by alexrv0922** [comment]
Done!
