### ISSUE TITLE
Children Info Tab

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#110]
1. "Children Info Tab" move it to the Customer Info Tab right below the " # of Children
2.  Depending on the number selected, the corresponding number of fields should appear in the Children's Tab. 

For example:  When " 1 " is selected. The Children Tab will appear with these options:

Child 1 - Name  
Child 1 - D.O.B.  
Child 1 - Gender  
Child 1 - Social

The rest should be invisible.

When the number 2 is selected, the first 8 fields should be visible and the rest should be invisible

When the number 3 is selected, the first 12 fields should be visible and the rest invisible.

When the number 4 is selected, all the fields should be visible.

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
This is great, there is just one thing to be fixed: 

When the number 1 is selected, the first 4 fields should be visible, and the rest invisible. 


When the number 2 is selected, the first 8 fields should be visible and the rest should be invisible

When the number 3 is selected, the first 12 fields should be visible and the rest invisible.

When the number 4 is selected, all the fields should be visible.

**Comment by gocastillo** [comment]
Take the fields in the Tab and put them on th Customer Info, just like you did with the Contact Spouse. 

When " 1 " is selected. The Children Tab will appear with these options:

Child 1 - Name
Child 1 - D.O.B.
Child 1 - Gender
Child 1 - Social

When "2"is selected, these fields should appear:

Child 1 - Name
Child 1 - D.O.B.
Child 1 - Gender
Child 1 - Social

Child 2 - Name
Child 2 - D.O.B.
Child 2 - Gender
Child 2 - Social

When "3"is selected, these fields should appear:

Child 1 - Name
Child 1 - D.O.B.
Child 1 - Gender
Child 1 - Social

Child 2 - Name
Child 2 - D.O.B.
Child 2 - Gender
Child 2 - Social

Child 3 - Name
Child 3 - D.O.B.
Child 3 - Gender
Child 3 - Social

When "4"is selected, these fields should appear:

Child 1 - Name
Child 1 - D.O.B.
Child 1 - Gender
Child 1 - Social

Child 2 - Name
Child 2 - D.O.B.
Child 2 - Gender
Child 2 - Social

Child 3 - Name
Child 3 - D.O.B.
Child 3 - Gender
Child 3 - Social

Child 4 - Name
Child 4 - D.O.B.
Child 4 - Gender
Child 4 - Social
