### ISSUE TITLE
Add these fields to the Ancilliary Tab:

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#112]
Please add these fields to the top of the form:

Priority Code  
Lead Source 
Partner 
Home Insurance Policy # 
Writing Agent  
Scrubber

These should be the first fields so make it a 2 column wit these on the first column and these on the second ( these are the ones that you added already) :

Accident  
Critical Illness  
Anciallary Total  
Hospital Confinement  
Dental Care

**Comment by alexrv0922** [comment]
Done!
