### ISSUE TITLE
"Mailing Address Different" fix

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#120]
In the Agent Layout form, the field " Mailing Address Different" has a check box, please change this to a dropdown with a Yes /No 

When the Yes is selected it should display a fields called:

"Mailing Address"

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Sorry for so many changes.
1. Go back to the check box, Cory likes how it worked.
2. Please make sure that when that checkbox is marked these fields will populate:
   - Mailing Address
   - Mailing City 
   - Mailing State
   - Mailing Zip Code

**Comment by alexrv0922** [comment]
Done!
