### ISSUE TITLE
To Do List  "+ New"  button

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#131]
This button should display a pop or take you to a page where that have these fields:
1. Subject
2. Reminder ( This one will let them choose a  day and time for a reminder)
3. Task Type  ( This will have a dropdown with the options: Appointment / Call / Email / CallBack )
4. Private  ( this will have a checkbox next to it)
5. Description   ( this will have a box to leave comments)
6.  Send notification email
7. There should be 3 buttons at the bottom, of  this page or pop up:
   - Save ( This will save the task and close the page or pop up)
   - Save & New ( this will save the task and clear the fields to create a new task)
     - Cancel  ( This will close the page without saving)

**Comment by alexrv0922** [comment]
Done!
