### ISSUE TITLE
Contact details Agent Layout

### ISSUE THREAD

**Issue by jchassoul** [machineio/fiorella#2]
Note from the underground the fist part of the form is a two column of 43 items in average.

following #1 

Management team and client, provides the following fields required by client.

Auto - Priority Code
Lead Source
Writing Agent
Partner
Health Writing Agent 
Lead Type
Health Lead Status
2016 Renewal Source
2016 Renewal Agent
Home Lead Status
2016 Renewal Submitter
Auto Lead Status
2016 Presold Processor
Flood Lead Status
Scrubber
Other Policy Sold
Last Modified By
Dental Lead Status
Federal Do Not Call
Do you own your home?
Renew As Is Email Received
Language Preference
First Name
Last Name
Phone
Cell Phone
Client Email
Other Phone
Date of Birth
Gender
Social Security Number
US Citizen or Legal Permanent Resident?
Mailing Address
State
City
ZipCode
Property Address Different
County
Marketplace Email
Property Address
Property City
Property State
Property Zip Code

Development team translates to both camel case and underscore variables.

autoPriorityCode auto_priority_code
leadSource lead_source
writingAgent writing_agent
partner partner
healthWritingAgent healt_writing_agent
leadType lead_type
healthLeadStatus healt_lead_status
2016RenewalSource 2016_renewal_source
2016RenewalAgent 2016_renewal_agent
homeLeadStatus home_lead_status
2016RenewalSubmitter 2016_renewal_submitter
autoLeadStatus auto_lead_status
2016PresoldProcessor 2016_presold_processor
floodLeadStatus flood_lead_status
scrubber scrubber
otherPolicySold other_policy_sold
LastModifiedBy last_modified_by
dentalLeadStatus dental_lead_status
federalDoNotCall federal_do_not_call
doYouOwnYourHome Do_you_own_your_home
renewAsIsEmailReceived renew_as_is_email_received
languagePreference language_preference
firstName first_name
lastName last_name
phone phone
cellPhone cell_phone
clientEmail client_email
otherPhone   other_phone
dateOfBirth date_of_birth
gender gender
socialSecurityNumber social_security_number
usCitizenOrLegalPermanentResident us_citizen_or_legal_permanent_resident
mailingAddress mailing_address
state state
city city
zipCode zip_code
propertyAddressDifferent property_address_different
county county
marketplaceEmail marketplace_email
propertyAddress property_address
propertyCity property_city
propertyState property_state
propertyZipCode property_zip_ode

For HTML ids we use the follow format:

auto-priority-code
lead-source
writing-agent
partner
health-writing-agent 
lead-type
health-lead-status
2016r-renewal-source
2016-renewal-agent
home-lead-status
2016-renewal-submitter
auto-lead-status
2016-presold-processor
flood-lead-status
scrubber
other-policy-sold
last -modified-by
dental-lead-status
federal-do-not -call
do-you-own-your-home
renew-as-is-email-received
language-preference
first-name
last-name
phone
cell-phone
client-email
other-phone
date-of-birth
gender
social-security-number
us-citizen-or-legal-permanent-resident
mailing-address
state
city
zip-code
property-address-different
county
marketplace-email
property-address
property-city
property-state
property-zip-code

HTML Translate strings:

autoPriorityCode: "Auto - Priority Code",
leadSource: "Lead Source",
writingAgent: "Writing Agent",
partner: "Partner",
healthWritingAgent: "Health Writing Agent" 
leadType: "Lead Type",
healthLeadStatus: "Health Lead Status",
2016RenewalSource: "2016 Renewal Source",
2016RenewalAgent: "2016 Renewal Agent",
homeLeadStatus: "Home Lead Status",
2016RenewalSubmitter: "2016 Renewal Submitter",
AutoLeadStatus: "Auto Lead Status", 
2016PresoldProcessor: "2016 Presold Processor",
floodLeadStatus: "Flood Lead Status",
scrubber: "Scrubber",
otherPolicySold: "Other Policy Sold",
lastModifiedBy: "Last Modified By",
dentalLeadStatus: "Dental Lead Status",
federalDoNotCallFederalDoNotCall: "Federal Do Not Call Federal Do Not Call",
doYouOwnYourHome: "Do you own your home?",
renewAsIsEmailReceived: "Renew As Is Email Received",
languagePreference: "Language Preference",
firstName: "First Name",
lastName: "Last Name",
phone: "Phone",
cellPhone: "Cell Phone",
clientEmail: "Client Email",
otherPhone: "Client Email",
dateOfBirth: "Date of Birth",
gender: "Gender",
socialSecurityNumber: "Social Security Number",
usCitizenOrLegalPermanentResident: "US Citizen or Legal Permanent Resident?",
mailingAddress: "Mailing Address",
state: "State",
city: "City",
zipCode: "ZipCode",
propertyAddressDifferent: "Property Address Different",
county: "County",
marketplaceEmail: "Marketplace Email",
propertyAddress: "Property Address",
propertyCity: "Property City",
propertyState: "Property State",
propertyZipCode: "Property Zip Code",

**Comment by gocastillo** [comment]
FIELDS: 

- Auto-Priority Code
- LeadSource

**Comment by alexrv0922** [comment]
Ready.

**Comment by gocastillo** [comment]
Add this options between Auto- Priority Code and Writing Agent:

Lead Type     ( This one must have a dropdown with options with checkboxes)   
[    ] Health Insurance
[    ] Homeowners Insurance
[    ] Auto Insurance
[    ] Life Insurance
[    ] Indemnity  
 
 
When one of these boxes is checkmarked it will make VISIBLE the corresponding tab.  Otherwise the tabs (Health INsurance, Homeowner's Insurance, Auto Insurance, etc)  are INVISIBLE.

**Comment by gocastillo** [comment]
Add the following fields before "Health Writing Agent":

Lead Source
Partner
2016 Renewal Source
2016 Renewal Agent
2016 Presold Processor
Scrubber
Last Modified by

Development team translates to both camel case and underscore variables.

leadSource lead_source
partner partner
2016RenewalSource  2016_renewal_source
2016RenewalAgent  2016_renewal_agent
2016PresoldProcessor  2016_presold_procesor
Scrubber scrubber
LastModifiedBy   last_modified_by


For HTML ids we use the follow format:

lead-source
partner
2016-renewal-source
2016-renewal-agent
2016-presold-processor
scrubber
last-modified-by

HTML Translate strings:

leadSource: "Lead Source",
partner: "Partner",
2016RenewalSource: "2016 Renewal Source",
2016RenewalAgent: "2016 Renewal Agent",
2016PresoldProcessor: "2016 Presold Processor",
scrubber: "Scrubber",
lastModifiedBy: "Last Modified by",
