### ISSUE TITLE
dashboard UI changes

### ISSUE THREAD

**Issue by ulillo** [machineio/fiorella#21]
- separate div summary of latest records 
- the division between the div of summary and latest records add a thin gray line (::
- change color of div by gray (#f3f4f7)

-remove the white background of list names of graph

**Comment by alexrv0922** [comment]
Ready!

**Comment by gocastillo** [comment]
Please check that the gray color matches with the division lines used on the rest of the page. The color used right now is rgb (104, 101 , 101)  and it    should be:    rgb (221, 221, 221)        => (#f3f4f7)

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Thanks. But it did not match what we where hoping for.

Please make one more change:

on that hr  remove the border style and make the color #eee

**Comment by alexrv0922** [comment]
Done!
