### ISSUE TITLE
tabs, buttons and sub menus

### ISSUE THREAD

**Issue by ulillo** [machineio/fiorella#26]
blue change in all sub menus,buttons and tabs for #858181

**Comment by alexrv0922** [comment]
Ready!

**Comment by gocastillo** [comment]
Please change the submenus color to #858181  in the Campaigns, Contacts and Events Tabs (All, Active, Ready, etc.)

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Under Dashboard, if you click in Campaigns, Events, Contacts and Tasks, there are some tabs in blue (All, Now, Later, Ready, Done). Please change those to #858181 .
