### ISSUE TITLE
" Homeowner's Insurance " Tab in Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#31]
Homeowner's Insurance

Note from the underground this part of the form is a two column of 39 items in average.

following #8

Management team and client, provides the following fields required by client.

New Purchase?             (Yes / No)
Home Exp Date/Closing Date            (Calendar)
Occupancy Status     (Vacation Property / Primary Residence / Seconday Residence / Seasonal Residence / Rental Property / Vacant For Sale / Renter)
Type of Dwelling     (Apartment / Single Family Home / Condo / Townhouse HO-6 / Townhouse HO-3 / Duplex, Mobile Home / Manufactured Home / Other) 
Current Home Carrier
Current Home Premium
Current Dwelling Coverage
Year Built
Square Ft. Under Air
Garage?
Construction Type         ( Masonery / Frame )
Stories
Age Roof
Roof Material
Bathrooms
Dog?
Pool?
Fence or Screen Enclosure?
Bankrupcy or Foreclosure in the past 5 years?       (Yes / No)
Centrally Monitored Alarm          (Yes / No / Burglar / Fire / Both )
Gated Community             (Yes / No)
How many Claims in the Last 5 Years?   ( 1 /2 / 3+ )
Realtor/Mortgage Broker
Amount of Personal Property
# of Stories in the Building

What floor # is Condo on?
Quote Update Request      ( Comment Field )
Home Policy Effective Date    ( Calendar )
4 Point (If Applicable)           [ checkbox ] 
Quoted Home Company  
Wind Mit              [ checkbox ]
Quoted Home Premium  
Quoted Home Number
Home Payment Option
Mortgage Clause (New)            (Comment field)
Loan #
Home Insurance Carrier             ( Escrowed / Client 1 Pay / Client 2 Pay / Client 3 Pay / Client 4 Pay / Client 8 Pay (Tapco) )
Home Insurance Premium
Home Insurance Policy #

Development team translates to both camel case and underscore variables.

newPurchase new_purchase
homeExpDateClosingDate 
home_exp_date_closing_date
occupancyStatus occupancy_status
typeOfDwelling type_of_dwelling
currentHomeCarrier current_home_carrier
currentHomePremium current_home_premium
currentDwellingCoverage current_dwelling_coverage
yearBuilt yearBuilt
squareFt.UnderAir Square Ft. Under Air
garage garage
constructionType construction_type
stories stories
ageRoof age_roof
roofMaterial roof_material
bathrooms bathrooms
dog dog
pool pool
fenceOrScreenEnclosure fence_or_screen_enclosure
bankrupcyOrForeclosureInThePastFiveYears bankrupcy_or_Foreclosure_in_the_past_5_years
centrallyMonitoredAlarm centrally_monitored_alarm
gatedCommunity gated_community
howManyClaimsInTheLastFiveYears how_many_claims_in_the_last_5_years
realtorMortgageBroker realtor_mortgage_broker
amountOfPersonalProperty amount_of_personal_property
numberOfStoriesInTheBuilding #_of_stories_in_the_building
WhatFloorIsCondoOn what_floor_#_is_condo_on
quoteUpdateRequest quote_update_request
homePolicyEffectiveDate home_policy_effective_date
FourPointIfApplicable 4_point_if_applicable
quotedHomeCompany 
quoted_home_company
windMit wind_mit
quotedHomePremium quoted_home_premium
quotedHomeNumber quoted_home_number
HomePaymentOption home_payment_option
mortgageClauseNew mortgage_clause_new
loanNumber loan_#
homeInsuranceCarrier home_insurance_carrier 
homeInsurancePremium home_insurance_premium
homeInsurancePolicyNumber home_insurance_policy_#

For HTML ids we use the follow format:

new-purchase-? 
home-exp-date-closing-date
occupancy-status
type-of-dwelling
current-home-carrier
current-home-premium
current-dwelling-coverage
year-built
square-ft-under-air
garage-?
construction-type
stories
age-roof
roof-material
bathrooms
dog-?
pool-?
fence-or-screen-enclosure-?
bankrupcy-or-Foreclosure-in-the-past-5-years-?
centrally-monitored-alarm
gated-community
how-many-claims-in-the-last-5-Years-?
realtor-mortgage-broker
amount-of-personal-property
# -of-stories-in-the-building

what-floor-#-is-condo-on-?
quote-update-request
home-policy-effective-date
4-point-if-applicable
quoted-home-company
wind-mit
quoted-home-premium
quoted-home-number
home-payment-option
mortgage-clause-new
loan-#
home-insurance-carrier 
home-insurance-premium
home-insurance-policy-#

HTML Translate strings:

newPurchase: "New Purchase?", 
homeExpDateClosingDate: "Home Exp Date/Closing Date",
occupancyStatus: "Occupancy Status",
typeOfDwelling: "Type of Dwelling",
currentHomeCarrier: "Current Home Carrier",
currentHomePremium: "Current Home Premium",
currentDwellingCoverage: "Current Dwelling Coverage",
yearBuilt: "Year Built",
squareFtUnderAir: "Square Ft. Under Air",
garage: "Garage?",
constructionType: "Construction Type",
stories: "Stories",
ageRoof: "Age Roof",
roofMaterial: "Roof Material",
bathrooms: "Bathrooms",
dog: "Dog?",
pool: "Pool?",
fenceOrScreenEnclosure: "Fence or Screen Enclosure?",
bankrupcyOrForeclosureInThePastFiveYears: "Bankrupcy or Foreclosure in the past 5 years?",
centrallyMonitoredAlarm: "Centrally Monitored Alarm",
gatedCommunity: "Gated Community",
howManyClaimsInTheLastFiveYears: "How many Claims in the Last 5 Years?",
realtorMortgageBroker: "Realtor/Mortgage Broker",
amountOfPersonalProperty: "Amount of Personal Property",
NumberOfStoriesInTheBuilding: "# of Stories in the Building",
whatFloorNumberIsCondoOn: "What floor # is Condo on?",
QuoteUpdateRequest: "Quote Update Request",
homePolicyEffectiveDate:"Home Policy Effective Date",
FourPointIfApplicable: "4 Point (If Applicable)",
quotedHomeCompany: "Quoted Home Company"
windMit: "Wind Mit",
quotedHomePremium: "Quoted Home Premium",
quotedHomeNumber: "Quoted Home Number",
homePaymentOption: "Home Payment Option",
MortgageClauseNew: "Mortgage Clause (New)",
loanNumber: "Loan #",
homeInsuranceCarrier: "Home Insurance Carrier", 
homeInsurancePremium: "Home Insurance Premium",
homeInsurancePolicyNumber": Home Insurance Policy #",

**Comment by alexrv0922** [comment]
Done!
