### ISSUE TITLE
" Automobile Insurance " Tab in Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#32]
Note from the underground this part of the form is a two column of 36  items in average.

following #9

Management team and client, provides the following fields required by client.

Current Auto Carrier  
Expiration Date           ( Calendar )
Current Auto Premium 
Current Residence Type                  ( Home / Rent / Live with Parents / Other)
Driver 1 License #
Vehicle 1 VIN
Vehicle 1 Year
Vehicle 1 Make
Vehicle 1 Model
Driver 2 License #
Vehicle 2 VIN
Vehicle 2 Year
Vehicle 2 Make
Vehicle 2 Model
Bodily Injury Liability
Property Damage
Uninsured Motorist Liability
Medical Payments
Vehicle 1 Comp Ded
Vehicle 1 Collision Ded
Auto 1 Towing                    (Yes / No ) 
Auto 1 Rental Car            (Yes / No )
Vehicle 2 Comp Ded
Vehicle 2 Collision Ded
Auto 2 Towing                   (Yes / No )
Auto 2 Rental Car           (Yes / No )
Quote Update Request               ( Comment Field )
Auto Policy Effective Date     ( Calendar )
Payment Option                  ( Pay in Full / EFT Monthly / Non EFT Monthly )
Auto Payment Info            ( Comment Field )
Quoted Auto Company              ( AIC / Allied/Nationwide / Foremost / GMAC/National General / Infinity / Progresive / Safeco / Travelers )
Quoted Auto Premium
Quoted Auto Number
Auto Insurance Carrier               ( AIC / Allied/Nationwide / Foremost / GMAC/National General / Infinity / Progresive / Safeco / Travelers )
Auto Insurance Premium 
Auto Insurance Policy #

Development team translates to both camel case and underscore variables.

currentAutoCarrier current_auto_carrier
expirationDate expiration_date
currentAutoPremium current_auto_premium
currentResidenceType current_residence_type
driverOneLicense driver_1_license_#
vehicleOneVin vehicle_1_vin
vehicleOneYear vehicle_1_year
vehicleOneMake vehicle_1_make
vehicleOneModel vehicle_1_model
driverTwoLicense driver_2_license_#
vehicleTwoVin vehicle_2_vin
vehicleTwoYear vehicle_2_year
vehicleTwoMake vehicle_2_make
vehicleTwoModel vehicle_2_model
bodilyInjuryLiability bodily_injury_liability
propertyDamage property_damage
uninsuredMotoristLiability uninsured_motorist_liability
medicalPayments medical_payments
vehicleOneCompDed vehicle_1_comp_ded
vehicleOneCollisionDed vehicle_1_collision_ded
autoOneTowing auto_1_towing
autoOneRentalCar auto_1_rental_car
vehicleTwoCompDed vehicle_2_comp_ded
vehicleTwoCollisionDed vehicle_2_collision_ded
autoTwoTowing auto_two_towing
autoTwoRentalCar auto_2_rental_car
quoteUpdateRequest quote_update_request
autoPolicyEffectiveDate auto_policy_effective_date
paymentOption payment_option
autoPaymentInfo auto_payment_info
quotedAutoCompany Qquoted_auto_company
quotedAutoPremium quoted_auto_premium
quotedAutoNumber quoted_auto_number
autoInsuranceCarrier auto_insurance_carrier
autoInsurancePremium auto_insurance_premium
autoInsurancePolicy auto_insurance_policy_#

For HTML ids we use the follow format:

current-auto-carrier
expiration-date
current-auto-premium
current-residence-type
driver-1-license-#
vehicle-1-vin
vehicle-1-year
vehicle-1-make
vehicle-1-model
driver-2-license-#
vehicle-2-vin
vehicle-2-year
vehicle-2-make
vehicle-2-model
bodily-injury-liability
property-damage
uninsured-motorist-liability
medical-payments
vehicle-1-comp-ded
vehicle-1-collision-ded
auto-1-towing
auto-1-rental-car
vehicle-2-comp-ded
vehicle-2-collision-ded
auto-2-towing
auto-2-rental-car
quote-update-request
auto-policy-effective-date
payment-option
auto-payment-info
quoted-auto-company
quoted-auto-premium
quoted-auto-number
auto-insurance-carrier
auto-insurance-premium
auto-insurance-policy-#

HTML Translate strings:

currentAutoCarrier: "Current Auto Carrier",
expirationDate: "Expiration Date",
currentAutoPremium: "Current Auto Premium",
currentResidenceType: "Current Residence Type",
driverOneLicense: "Driver 1 License#",
vehicleOneVin: "Vehicle 1 VIN",
vehicleOneYear: "Vehicle 1 Year",
vehicleOneMake: "Vehicle 1 Make",
vehicleOneModel: "Vehicle 1 Model",
driverTwoLicense#: "Driver 2 License#",
vehicleTwoVin: "Vehicle 2 VIN",
vehicleTwoYear: "Vehicle 2 Year",
vehicleTwoMake: "Vehicle 2 Make",
vehicleTwoModel: "Vehicle 2 Model",
bodilyInjuryLiability: "Bodily Injury Liability",
propertyDamage: "Property Damage",
uninsuredMotoristLiability: "Uninsured Motorist Liability",
medicalPayments: "Medical Payments",
vehicleOneCompDed: "Vehicle 1 Comp Ded",
vehicleOneCollisionDed: "Vehicle 1 Collision Ded",
autoOneTowing: "Auto 1 Towing",
autoOneRentalCar: "Auto 1 Rental Car",
vehicleTwoCompDed: "Vehicle 2 Comp Ded",
vehicleTwoCollisionDed: "Vehicle 2 Collision Ded",
autoTwoTowing: "Auto 2 Towing",
autoTwoRentalCar: "Auto 2 Rental Car",
quoteUpdateRequest: "Quote Update Request",
autoPolicyEffectiveDate: "Auto Policy Effective Date",
paymentOption: "Payment Option",
autoPaymentInfo: Auto Payment Info
quotedAutoCompany: "Quoted Auto Company",
quotedAutoPremium: "Quoted Auto Premium",
quotedAutoNumber: "Quoted Auto Number",
autoInsuranceCarrier: "Auto Insurance Carrier",
autoInsurancePremium: "Auto Insurance Premium",
autoInsurancePolicy: "Auto Insurance Policy#",

**Comment by alexrv0922** [comment]
Done!
