### ISSUE TITLE
Restructure of  the Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#37]
The Agent Layout form so far only includes the Health Insurance part. This Health Lead would include the 4th, 5th and 6th tab (2015 Coverage, 2015 Plan Selections and 2016 Plan Selections.

Make these 3 into 1 Tab called "Health Insurance".

**Comment by gocastillo** [comment]
Add the "2016 Processed Information"  Fields to the Health Insurance Tab

**Comment by alexrv0922** [comment]
Done!
