### ISSUE TITLE
Add Lead Type Option to Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#38]
Add this options between Auto- Priority Code and Writing Agent:

Lead Type     ( This one must have a dropdown with options with checkboxes)
[    ] Health Insurance
[    ] Homeowners Insurance
[    ] Auto Insurance
[    ] Life Insurance
[    ] Indemnity  

When one of these boxes is checkmarked it will make VISIBLE the corresponding tab.  Otherwise the tabs (Health INsurance, Homeowner's Insurance, Auto Insurance, etc)  are INVISIBLE.

**Comment by alexrv0922** [comment]
Done!
