### ISSUE TITLE
Add missing fields to Agent Layout Form

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#39]
Add the following fields before "Health Writing Agent":

Lead Source
Partner
2016 Renewal Source
2016 Renewal Agent
2016 Presold Processor
Scrubber
Last Modified by

Development team translates to both camel case and underscore variables.

leadSource lead_source
partner partner
2016RenewalSource  2016_renewal_source
2016RenewalAgent  2016_renewal_agent
2016PresoldProcessor  2016_presold_procesor
Scrubber scrubber
LastModifiedBy   last_modified_by

For HTML ids we use the follow format:

lead-source
partner
2016-renewal-source
2016-renewal-agent
2016-presold-processor
scrubber
last-modified-by

HTML Translate strings:

leadSource: "Lead Source",
partner: "Partner",
2016RenewalSource: "2016 Renewal Source",
2016RenewalAgent: "2016 Renewal Agent",
2016PresoldProcessor: "2016 Presold Processor",
scrubber: "Scrubber",
lastModifiedBy: "Last Modified by",

**Comment by alexrv0922** [comment]
Done!
