### ISSUE TITLE
Contact details Current Job and Income Information

### ISSUE THREAD

**Issue by jchassoul** [machineio/fiorella#4]
@gocastillo , please add here the fields of the second sub form, using the same format that use specify on issue #1

**Comment by gocastillo** [comment]
Note from the underground the second part of the form is a two column of 7 items in average.

following #2

Management team and client, provides the following fields required by client.

Total INDIVIDUAL Inncome
Total HOUSEHOLD Income
Primary Applicant's Income Source
Primary Applicant's Employer's Name
Applicant Employers Phone Number
Marital Status
Number of Dependent Children In House

Development team translates to both camel case and underscore variables.

totalIndividualIncome total_individual_income
totalHouseholdIncome total_household_income
primaryApplicantsIncomeSource primary_applicant's_income_source
primaryApplicantsEmployersName primary_applicants_employers_name
applicantEmployersPhoneNumber applicant_employers_phone_number
maritalStatus marital_status
numberOfDependentChildrenInHouse number_of_dependent_children_in_house

For HTML ids we use the follow format:

total-individual-income
total-household-income
primary-applicants-income-source
primary-applicants-employer's-name
applicant-employers-phone-number
marital -status
number-of-dependent-children-in-house

HTML Translate strings:

totalIndividualIncome: "Total INDIVIDUAL Inncome",
totalHouseholdIncome: "Total HOUSEHOLD Income",
primaryApplicantsIncomeSource: "Primary Applicant's Income Source",
primaryApplicantsEmployersName: "Primary Applicant's Employer's Name",
applicantEmployersPhoneNumber: "Applicant Employers Phone Number",
maritalStatus: "Marital Status",
numberOfDependentChildrenInHouse:  "Number of Dependent Children In House",
