### ISSUE TITLE
Life Insurance Tab

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#49]
Life Insurance

Note from the underground this part of the form is a two column of 17items in average.

Management team and client, provides the following fields required by client.

Age
Height
Weight

Life Insurance Type
Term Life Policy Lenght
Desired Amount of Coverage
Smoke?
Major Health Issues in relatives?
Convicted of drunk driving?

---

Life Quote Status

Date Paramed Exam Ordered   (calendar)
Life Monthly Premium
Paramed Company

Life Application ID #
Life Application Status
Life Application Changes
Life After Changes New Premium
Life Application Declined Reason

Development team translates to both camel case and underscore variables.

age   age
height   height
weight   weight

lifeInsuranceType   life_insurance_type
termLifePolicyLenght  term_life_policy_lenght
desiredAmountOfCoverage  desired_amount_of_coverage
smoke   smoke_?
majorHealthIssuesInRelatives   major_health_issues_in_relatives_?
convictedOfDrunkDriving   convicted_of_drunk_driving

---

lifeQuoteStatus   life_quote_status

dateParamedExamOrdered  date_paramed_exam_ordered
lifeMonthlyPremium   life_monthly_premium
paramedCompany   paramed_company

lifeApplicationIDNumber  life_application_id_#
lifeApplicationStatus  life_application_status
lifeApplicationChanges  life_application_changes
lifeAfterChangesNewPremium  life_after_changes_new_premium
lifeApplicationDeclinedReason   life_application_declined_reason

For HTML ids we use the follow format:

age
height
weight

life-insurance-type
term-life-policy-lenght
desired-amount-of-coverage
smoke-?
major-health-issues-in-relatives-?
convicted-of-drunk-driving-?

---

life-quote-status

date-paramed-exam-ordered  
life-monthly-premium
paramed-company

life-application-id-#
life-application-status
life-application-changes
life-after-changes-new-premium
life-application-declined-reason

HTML Translate strings:

age: "Age",
height: "Height",
weight: "Weight",

lifeInsuranceType: "Life Insurance Type",
termLifePolicyLenght: "Term Life Policy Lenght",
desiredAmountOfCoverage: "Desired Amount of Coverage",
smoke: "Smoke?",
majorHealthIssuesInRelatives: "Major Health Issues in relatives?",
convictedOfDrunkDriving?: "Convicted of drunk driving?",

---

lifeQuoteStatus:"Life Quote Status",

dateParamedExamOrdered: "Date Paramed Exam Ordered",  
lifeMonthlyPremium
paramedCompany

lifeApplicationId: "Life Application ID",
lifeApplicationStatus: "Life Application Status",
lifeApplicationChanges: "Life Application Changes",
lifeAfterChangesNewPremium: "Life After Changes New Premium",
lifeApplicationDeclinedReason: "Life Application Declined Reason",

**Comment by gocastillo** [comment]
- The brackets "[  ]" indicate a checkbox 
- The horizontal line that appears between "Convicted of drunk driving?" and "Life Quote Status"  should appear in the form

**Comment by gocastillo** [comment]
PLease eliminate fields from 1 ( First Name) to  15 (Date of Birth) .      Also eliminate field  # 17 (Gender) and #18 ( Social Security Number)

**Comment by alexrv0922** [comment]
Done!
