### ISSUE TITLE
Change fields to Agent Layout

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#61]
Change :

Health Lead Status
Home Lead Status
Auto Lead Status 
FLood Lead Status

to:

Health Insurance  ( Yes / No )
Home Insurance  (Yes / No )
Auto Insurance  (Yes / No )
Life Insurance  ( Yes/ No )
Ancilliary  ( Yes /No )

When these are marked as "Yes" the corresponding tab should appear.

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Please check because it's not activating the Tab.  
If you are going to use a checkbox then there is no need to us a parenthesis with Yes/No

**Comment by alexrv0922** [comment]
Done!
