### ISSUE TITLE
Change fields order in Agent Layout

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#67]
Change "Mailing Address" for "Property Address"

The field: "Property Address Different " should read " Mailing Address different. And this 
should have a checkbox next to it.

If the box is not checked then "Mailing Address" is invisible.  Iof it's checked, then this field should appear in the form.

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Thank you, not when the box is cheked, a field called "Mailing Address" should appear right below it.

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
The Mailing Address field should be invisible. And only visible if the box is checked

**Comment by alexrv0922** [comment]
Done!
