### ISSUE TITLE
Change Order of Info in Health Insurance Tab

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#68]
The most recent information should go on top. In this case the order should be:
 2016  and then 2015

**Comment by alexrv0922** [comment]
Need more info...

**Comment by gocastillo** [comment]
Job/Income  ...  (see issue #66)
2016 Processed Information
2016 Plan Selection
2015 Contact Info
2015 Plan Selection

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
At the very top the first section shoud be "Current Job Income Info"
