### ISSUE TITLE
Contact details 2015 Current Coverage

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#7]

**Comment by gocastillo** [comment]
Note from the underground the fourth part of the form is a two column of 7 items in average.

following #4

Management team and client, provides the following fields required by client.

Lead Has a Marketplace Account
Current Coverage
2015 Marketplace App ID
Current Premium
Subsidy Amount
Current Net Premium
2015 Effective Date

Development team translates to both camel case and underscore variables.

leadHasAMarketplaceAccount lead_has_a_marketplace_account
currentCoverage current_coverage
2015MarketplaceAppID 2015_marketplace_app_id
currentPremium current_premium 
subsidyAmount subsidy_amount
currentNetPremium current_net_premium
2015EffectiveDate 2015_effective_date

For HTML ids we use the follow format:

lead-has-a-marketplace-account
current-coverage
2015-marketplace-app-id
current-premium
subsidy-amount
current-net-premium
2015-effective-date

HTML Translate strings:

leadHasAMarketplaceAccount: "Lead Has a Marketplace Account",
currentCoverage: "Current Coverage",
2015MarketplaceAppID: "2015 Marketplace App ID",
currentPremium: "Current Premium",
subsidyAmount: "Subsidy Amount",
currentNetPremium: "Current Net Premium",
2015EffectiveDate: "2015 Effective Date",

**Comment by alexrv0922** [comment]
Had to make a little change in the name of 4 variables:

2015MarketplaceAppID  =>  marketplaceAppID2015
2015_marketplace_app_id  =>  marketplace_app_id_2015
2015EffectiveDate  =>   effectiveDate2015
2015_effective_date  =>  effective_date_2015

That's because variables in javascript can't start with numbers.

**Comment by alexrv0922** [comment]
And also the id's:

2015-marketplace-app-id  =>  marketplace-app-id-2015
2015-effective-date  =>  effective-date-2015

**Comment by gocastillo** [comment]
I'll change the variables on the remaining tasks. 

Please fix the last field on this part of the form: 2015EffectiveDate should have spaces => 2015 Effective Date
