### ISSUE TITLE
Move the Health Writing Agent field and US Citizen

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#72]
The "Health Writing Agent" and "US Citizen or Legal Permanent Resident?"field should go in the Health Insurance Tab

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
US Citizen or Legal Permanent Resident? 
Writing Agent  
Scrubber

These should go after the first 4 fields mentioned in issue # 78
