### ISSUE TITLE
Add Priority Code, Lead Source and Partner to all Insurance Tabs

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#78]
Add the fields:
- Priority Code
- Lead Source
- Partner 

To all Insurance Tabs.

**Comment by alexrv0922** [comment]
In the health insurance tab. Where should I put this??

**Comment by gocastillo** [comment]
OK actually these 3 fields should be the first 3 along with the Health Insurance Status. Just put them at the top of the sorm, before any other title.   So:

Priority Code
Lead Source
Partner
Health Insurance

And then please move " Current Job Info" between these fields and 2016 Processed Info :).

**Comment by gocastillo** [comment]
Oh and please make these 4 fields the first 4 in all insurances. Thanks!!
