### ISSUE TITLE
2015 Plan Selections

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#8]
Please check and fix :
 Quoted Renewal Gross Premium should be

2016 Quoted Renewal Gross Premium

**Comment by gocastillo** [comment]
Note from the underground the fifth part of the form is a two column of 16 items in average.

following #5

Management team and client, provides the following fields required by client.

2015 Application ID#
2015 Health Premium
2015 Health Carrier
2015 Subsidy
2015 Adults on Plan
2015 Child(ren) on Plan
Income Verification Needed
Citizenship Documents Needed
Username
Password
Health Policy#
Agent Code
Wants to renew same plan for 2016
2016 Quoted Renewal Gross Premium
2016 Quoted Renewal Subsidy
2016 Quoted Renewal Net Premium

Development team translates to both camel case and underscore variables.

2015ApplicationId 2015_application_id
2015HealthPremium 2015_health_premium
2015HealthCarrier 2015_health_carrier
2015Subsidy 2015_subsidy
2015AdultsOnPlan 2015_adult_on_plan
2015ChildrenOnPLan 2015_children_on_plan
IncomeVerificationNeeded income_verification_needed
CitizenshipDocumentsNeeded citizenship_documents_needed
username username
password password
healthPolicy health_policy
agentCode agent_code
wantsToRenewSamePlanFor2016 wants_to_renew_same_plan_for_2016
2016QuotedRenewalGrossPremium 2016_quoted_renewal_gross_premium
2016QuotedRenewalSubsidy 2016_quoted_renewal_subsidy
2016QuotedRenewalNetPremium 2016_quoted_renewal_net_premium

For HTML ids we use the follow format:

2015-application-id
2015-health-premium
2015-health-carrier
2015-subsidy
2015-adult-on-plan
2015-children-on-plan
income-verification-needed
citizenship-documents-needed
username
password
health-policy
agent-code
wants-to-renew-same-plan-for-2016
2016-quoted-renewal-gross-premium
2016-quoted-renewal-subsidy
2016-quoted-renewal-net-premium

HTML Translate strings:

2015ApplicationId: "2015 Application ID#",
2015HealthPremium: "2015 Health Premium",
2015HealthCarrier: "2015 Health Carrier",
2015Subsidy: "2015 Subsidy",
2015AdultsOnPlan: "2015 Adults on Plan",
2015ChildrenOnPlan: "2015 Child(ren) on Plan",
IncomeVerificationNeeded: "Income Verification Needed",
CitizenshipDocumentsNeeded: "Citizenship Documents Needed",
Username: "Username",
Password: "Password",
healthPolicy: "Health Policy",
agentCode: "Agent Code",
wantsToRenewSamePlanFor2016: "Wants to renew same plan for 2016",
2016QuotedRenewalGrossPremium2016: "Quoted Renewal Gross Premium",
2016QuotedRenewalSubsidy: "2016 Quoted Renewal Subsidy",
2016QuotedRenewalNetPremium: "2016 Quoted Renewal Net Premium",

**Comment by gocastillo** [comment]
Please add the "# " symbol to the Health Policy field

**Comment by alexrv0922** [comment]
Done!
