### ISSUE TITLE
Payment Information Tab

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#83]
Payment Information

Note from the underground this part of the form is a two column of 12 items .

Management team and client, provides the following fields required by client.

Binder Payment Option  
Payment Charge Request
Credit Card Type  
Name on CC  
Credit Card Number
CC Expiration Date  
CC CVV  
Bank Account Type  
Bank Name  
Bank Routing Number 
Bank Account Number

Development team translates to both camel case and underscore variables.

binderPaymentOption           binder_payment_option
paymentChargeRequest           payment_charge_request
creditCardType       credit_card_type
nameOnCc        name_on_cc
creditCardNumber      credit_card_number
ccExpirationDate      cc_expiration_date
bankAccountType      bank_account_type
bankName   bank_name
bankRoutingNumber      bank_routing_number
bankAccountNumber      bank_account_number

For HTML ids we use the follow format:

binder-payment-option
payment-charge-request
ccredit-card-type
name-on-cc
credit-card-number
cc-expiration-date
bank-account-type
bank-name
bank-routuing-number
bank-account-number

HTML Translate strings:

binderPaymentOption: " Binder Payment Option",
paymentChargeRequest: "Payment Charge Request",
creditCardType:   "Credit Card Type",
nameOnCc:  "Name on CC",
creditCardNumber:    "Credit Card Number",
ccExpirationDate:   "CC Expiration Date",
bankAccountType:  "Bank Account Type",
bankName:  "Bank Name",
bankRoutingNumber:  "Bank Routing Number",
bankAccountNumber:  Bank Account Number",

**Comment by gocastillo** [comment]
Please eliminate these fields form the 2016 Plan Selection in the Health Insurance Tab

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
1) Create a "Payment Information" Tab with the fields listed above. 

2) This tab should only be visible when the Lead status is changed to "sold"   (see issue # 84)

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Thanks! 

I did forget to add one field. I'm sorry u.u  

Please add this field between  "CC Expiration Date" and "Bank Account Type"

CC CVV

**Comment by alexrv0922** [comment]
Done!
