### ISSUE TITLE
Lead Status dropdown

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#84]
These are the options that we need to add in the Health Lead Status, Home Lead Status, Auto Lead Status and Life Lead Status:

Presold
Enrolled
Bound
Active
Submitted
Sold

*****When the status "Sold" is selected the "Payment Information Tab" should appear in the form, otherwise it's invisible

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Excellent! Thamks :)
