### ISSUE TITLE
Move fields in Health Insurance Tab

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#87]
Under "2015 Contact Info"  please eliminate: 
- Health Lead Status  
- Health Writing Agent  
- US Citizen or Legal Permanent Resident?  
- Writing Agent 
- Scrubber 

These should be the first fields in the form. They dont have any title, just add them at the begining after Priority Code, Lead Source and Partner   (issue# 78)

**Comment by alexrv0922** [comment]
Done!
