### ISSUE TITLE
1st Tabs in Ancillary

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#88]
***These options should have a dropdown with these 2 options:   "Application Submitted"  and "Pending"   

When the status changes to Application submitted, that will activate the corresponding section ( see issues#92 to issue #95)

Except for the option:  "Ancilliary Total"***

Note from the underground the fist part of the form is a two column of 5 items in average.

Accident
Critical Illness
Hospital Confinement
Dental Care

Anciallary Total

Development team translates to both camel case and underscore variables.

accident accident
criticalIllness critical_illness
hospitalConfinementhospital_confinement
dentalCare dental_care 

ancillaryTotal ancillary_total

For HTML ids we use the follow format:

accident
critical-illness
hospital-confinement
dental-care

ancillary-total

HTML Translate strings:

accident: "Accident",
criticalIllness: "Critical Illness",
hospitalConfinemet: "Hospital Confinement",
dentalCare: "Dental Care",

ancillaryTotal: "Anciallary Total",

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
Thanks, this is almost perfect. In the dropdown the second option should be "Pending" instead of "Enrolled"

**Comment by alexrv0922** [comment]
Done!

**Comment by gocastillo** [comment]
One more thing. There are some spelling errors, sorry:

The Tab should be "Ancillary" 

And the field should be    "Ancillary Total"

Please fix

**Comment by gocastillo** [comment]
Thanks! 

Only one spelling error was missed, the name on the tab says "Ancilliary" but it should be "Ancillary".

And the field "Ancillary Total shoul be the last on that section, so please move it below Dental Care,
