### ISSUE TITLE
2nd section in Ancillary Tab : " Diagnosed or currently have "

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#89]
2nd section in Ancillary:

"Diagnosed or currently have"

Note from the underground the fist part of the form is a two column of 11  items in average.

Abnormal cancer screening test?
Cysts, growths, etc, not seen for?
Carotid Artery Stenosis, etc?
HIV positive, AIDS Related Complex, AIDS
Multiple sclerosis, memory loss, etc?
Abnormal tests requiring follow-up?
Any non-routine consultation scheduled?
1 or more imm relative with issues &
2 or more imm. relatives with issues &
Bening Tumor, hypertension, etc.?
Prescription medication in last 3 years

Development team translates to both camel case and underscore variables.

abnormalCancerScreeningTest   abnormal_cancer_screening_test_?
cystsGrowthsEtcNotSeenFor   cysts_,_growths_,_etc_,_not_seen_for_?
carotidArteryStenosisEtc    carotid_artery_Stenosis_,_ etc_?
hivPositiveAidsRelatedComplexAids   hiv_positive_aids_related_complex_,_aids
multipleSclerosisMemoryLossEtc   multiple_sclerosis_,_memory_loss_,_etc
abnormalTestsRequiringFollowUp   abnormal_tests_requiring_follow_up
anyNonRoutineConsultationScheduled  any_non_-_routine_consultation_scheduled_?
OneOrmoreImmRelativesWithIssues&    1_or_more_imm_relatives_with_issues_&
TwoOrMoreImmRelativesWithIssues&    2_or_more_imm_relatives_with_issues_&
beningTumorHypertensionEtc    bening_tumor_,_hypertension_,_etc_?
presciptionMedicationInLastThreeYears   prescription_medication_in_last_three_years

For HTML ids we use the follow format:

abnormal-cancer-screening-test
cysts-,-growths-,-ect-,-not-seen-for-?
carotid-artery-Stenosis-,-etc-?
hiv-positive-aids-related-complex-,-aids
multiple-sclerosis-,-memory-loss-,-etc
abnormal-tests-requiring-follow-up
any-non-routine-consultation-scheduled-?
1-or-more-imm-relatives-with-issues-&
2-or-more-imm-relatives-with-issues-&
bening_tumor-,-hypertension-,-etc-?
prescription-medication-in-last-three-years

HTML Translate strings:

abnormalCancerScreeningTest: "Abnormal cancer screening test?",
cystsGrowthsEtcNotSeenFor: "Cysts, growths, etc, not seen for?",
carotidArteryStenosisEtc: "Carotid Artery Stenosis, etc?",
hivPositiveAidsRelatedComplexAids: "HIV positive, AIDS Related Complex, AIDS", 
multipleSclerosisMemoryLossEtc : "Multiple sclerosis, memory loss, etc?",
abnormalTestsRequiringFollowUp : "Abnormal tests requiring follow-up?",
anyNonRoutineConsultationScheduled: "Any non-routine consultation scheduled?"
OneOrMoreImmRelativesWithIssues&: "1 or more imm relative with issues &",
TwoOrMoreImmRelativesWithIssues& : "2 or more imm. relatives with issues &",
beningTumorHypertensionEtc: "Bening Tumor, hypertension, etc.?",
presciptionMedicationInLastThreeYears: "Prescription medication in last 3 years",

**Comment by alexrv0922** [comment]
Done!
