### ISSUE TITLE
3rd section in Ancillary: "Diagnosed, been treated form or taken medication for..."

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#90]
Third section in Ancilliary: 
"Diagnosed, been treated form or taken medication for..."

Note from the underground the fist part of the form is a two column of 5 items in average.

Disorder/disease: Heart, Kidney, Lungs
Disease: Quad, Lou Gehrig's, Other motor
Alcohol or Substance Abuse (5 years)
Heart attack, stroke, transient ischemic
Diabetes Type 1 or 2, blood press & am

Development team translates to both camel case and underscore variables.

disorderDiseaseHeartKidneyLungs   disorder_disease_heart_kidney_lungs
diseaseQuadLouGehrigsOtherMotor   disease_quad_lou_gehrigs_other_motor
alcoholOrSubstanceAbuseFiveYears   alcohol_or_substance_abuse_five_years
heartAttackStrokeTransientIschemic   heart_attack_stroke_transient_ischemic
diabetesTypeOneOrTwoBloodPress&Am    diabetes_type_one_or_two_blood_press_&_am

For HTML ids we use the follow format:

disorder-disease-heart-kidney-lungs
disease-quad-lou-gehrigs-other-motor
alcohol-or-substance-abuse-five-years
heart-attack-stroke-transient-ischemic
diabetes-type-one-or-two-blood-press-&-am

HTML Translate strings:

disorderDiseaseHeartKidneyLungs: " Disorder/disease: Heart, Kidney, Lungs ",
diseaseQuadLouGehrigsOtherMotor: " Disease: Quad, Lou Gehrig's, Other motor  ",
alcoholOrSubstanceAbuseFiveYears: " Alcohol or Substance Abuse (5 years) ",
heartAttackStrokeTransientIschemis:  " Heart attack, stroke, transient ischemic ",
diabetesTypeOneOrTwoBloodPress&Am:  " Diabetes Type 1 or 2, blood press & am ",

**Comment by alexrv0922** [comment]
Done!
