### ISSUE TITLE
4th section in Ancilliary:  "Other Information"

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#91]
Fourth section in Ancilliary: 
"Other Information"

Note from the underground the fist part of the form is a two column of 6 items in average.

Nursing Home, hospitalized, etc?
Hospitalized in the last 12 months?
Diagnosed or treated for medical issues
Pregnant?
Ever had a problem pregnancy?
Hypertension?

Development team translates to both camel case and underscore variables.

nursingHomeHospitalizedEtc  nursing_home_hospitalized_etc
hospitalizedInTheLastTwelveMonths hospitalized_in_the_last_twelve_months
diagnosedOrTreatedForMedicalIssues diagnosed_or_treated_for_medical_issues
pregnant pregnant
everHadAProblemPregnancy ever_had_a_problem_pregnancy
hypertension hypertension

For HTML ids we use the follow format:

nursing-home-hospitalized-etc
hospitalized-in-the-last-twelve-months
diagnosed_or_treated_for_medical_issues
pregnant
ever_had_a_problem_pregnancy
hypertension

HTML Translate strings:

nursingHomeHospitalizedEtc: "Nursing Home, hospitalized, etc?",
hospitalizedInTheLastTwelveMonths: "Hospitalized in the last 12 months?",
diagnosedOrTreatedForMedicalIssues: "Diagnosed or treated for medical issues",
pregnant: "Pregnant?",
everHadAProblemPregnancy: "Ever had a problem pregnancy?",
hypertension: "Hypertension?",

**Comment by alexrv0922** [comment]
Done!
