### ISSUE TITLE
5th section in Ancilliary:  "Accident Elite"

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#92]
5th section in Ancilliary: 
"Accident Elite"

Note from the underground the fist part of the form is a two column of 3 items in average.

Accident Elite Request Eff Date
Accident Elite Premium
Accident Elite Notes

Development team translates to both camel case and underscore variables.

accidentEliteRequestEffDate    accident_elite_request_eff_date
accidentElitePremium    accident_elite_premium
accidentEliteNotes      accident_elite_notes

For HTML ids we use the follow format:

accident-elite-request_eff_date
accident-elite-premium
accident-elite-notes

HTML Translate strings:

accidentEliteRequest: "Accident Elite Request Eff Date",
accidentElitePremium: "Accident Elite Premium",
accidentEliteNotes: "Accident Elite Notes",

**Comment by alexrv0922** [comment]
Done!
