### ISSUE TITLE
6th section in Ancilliary:  "Critical Care"

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#93]
5th section in Ancilliary: 
"Critical Care"

Note from the underground the fist part of the form is a two column of 3 items in average.

Critical Care Request Eff Date
Critical Care Premium
Critical Care Notes

Development team translates to both camel case and underscore variables.

criticalCareRequestEffDate       critical_care_request_eff_date
criticalCarePremium    critial_care_premium
criticalCareNotes    critical_care_notes

For HTML ids we use the follow format:

critical-care-request-eff-date
critial-care-premium
critical-care-notes

HTML Translate strings:

criticalCareRequestEffDate: "Critical Care Request Eff Date",
criticalCarePremium: "Critical Care Premium",
criticalCareNotes: "Critical Care Notes",

**Comment by alexrv0922** [comment]
Done!
