### ISSUE TITLE
7th section in Ancilliary:  "Hospital Confinement"

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#94]
7th section in Ancilliary: 
"Hospital Confinement"

Note from the underground the fist part of the form is a two column of 3 items in average.

Request Eff Date
Hospital Confinement Premium
Hospital Confinement Notes

Development team translates to both camel case and underscore variables.

requestEffDate  request_eff_date
hospitalConfinementPremium   hospital_confinement_premium
hospitalConfinementNotes     hospital_confinement_notes

For HTML ids we use the follow format:

request-eff-date
hospital-confinement-premium
hospital-confinement-notes

HTML Translate strings:

requestEffDate: "Request Eff Date",
hospitalConfinementPremium: "Hospital Confinement Premium",
hospitalConfinementNotes: "Hospital Confinement Notes",

**Comment by alexrv0922** [comment]
Done!
