### ISSUE TITLE
8th section in Ancilliary:  "Dental Care"

### ISSUE THREAD

**Issue by gocastillo** [machineio/fiorella#95]
8th section in Ancilliary: 
"Dental Care"

Note from the underground the fist part of the form is a two column of 3 items in average.

Request Eff Date
Dental Care Premium
Dental Care Notes

Development team translates to both camel case and underscore variables.

requestEffDate  request_eff_date
dentalCarePremium   dental_care_premium
dentalCareNotes     dental_care_notes

For HTML ids we use the follow format:

request-eff-date
dental-care-premium
dental-care-notes

HTML Translate strings:

requestEffDate: "Request Eff Date",
dentalCarePremium: "Dental Care Premium",
dentalCareNotes: "Dental Care Notes",

**Comment by alexrv0922** [comment]
Done!
